name: 'Run Tests'
on:
  pull_request:
    branches:
      - main
      - develop
      - staging

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - name: 'Install Node'
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: 'Install Deps'
        run: npm install
      - name: 'Test'
        run: npx vitest --coverage.enabled true
      - name: 'Upload Coverage'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ github.head_ref }}
          path: coverage

  report-coverage:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.base_ref == 'main' || github.base_ref == 'develop' || github.base_ref == 'staging'
    steps:
      - name: 'Download Coverage Artifacts'
        uses: actions/download-artifact@v4
        with:
          name: coverage-${{ github.head_ref }}
          path: coverage
      - name: 'Report Coverage'
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          json-summary-compare-path: coverage/coverage-summary.json
          vite-config-path: ./vite.config.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
